//! Canonical close evidence for the existing Intercom reservation protocol.
use crate::{stable_json_bytes, CONTRACT_VERSION};
use serde_json::{json, Value};

pub const RESERVATION_BINDING_FIELDS: &[&str] = &[
    "billing_epoch",
    "reservation_id",
    "reservation_expires_after_epoch",
    "reservation_receipt_grace_epochs",
    "billing_id",
    "billing_attempt",
    "session_id",
    "user",
    "rail",
    "provider",
    "payout_revision",
];

pub fn reservation_binding_matches(binding: &Value, value: &Value) -> bool {
    RESERVATION_BINDING_FIELDS.iter().all(|key| {
        binding
            .get(*key)
            .is_some_and(|expected| !expected.is_null() && value.get(*key) == Some(expected))
    })
}

pub fn usage_reservation_close_value(
    binding: &Value,
    head: Option<&Value>,
    expiry: bool,
    at: u64,
    reason: &str,
) -> Result<Value, String> {
    if !reservation_binding_matches(binding, binding) {
        return Err("reservation close is missing its exact reservation binding".into());
    }
    let mut value = serde_json::Map::new();
    for key in RESERVATION_BINDING_FIELDS {
        value.insert((*key).into(), binding[*key].clone());
    }
    value.insert(
        "op".into(),
        json!(if expiry {
            "expire_usage_reservation"
        } else {
            "close_usage_reservation"
        }),
    );
    value.insert("contract_version".into(), json!(CONTRACT_VERSION));
    value.insert(
        "latest_receipt_seq".into(),
        head.map(|h| h["receipt_seq"].clone())
            .unwrap_or(Value::Null),
    );
    value.insert(
        "latest_receipt_hash".into(),
        head.map(|h| h["receipt_hash"].clone())
            .unwrap_or(Value::Null),
    );
    value.insert("at".into(), json!(at));
    value.insert("reason".into(), json!(reason));
    value.insert(
        "actor".into(),
        binding[if expiry { "user" } else { "provider" }].clone(),
    );
    value.insert(
        "actor_role".into(),
        json!(if expiry { "user" } else { "provider" }),
    );
    Ok(Value::Object(value))
}

pub fn usage_reservation_close_signing_bytes(value: &Value) -> Result<Vec<u8>, String> {
    let mut evidence = value.clone();
    evidence
        .as_object_mut()
        .ok_or("reservation close must be an object")?
        .remove("actor_sig");
    let prefix: &[u8] = match evidence["op"].as_str() {
        Some("close_usage_reservation") => b"mayhem-close-usage-reservation-v1",
        Some("expire_usage_reservation") => b"mayhem-expire-usage-reservation-v1",
        _ => return Err("unsupported reservation close operation".into()),
    };
    let mut bytes = prefix.to_vec();
    bytes.extend(stable_json_bytes(&evidence).map_err(|e| e.to_string())?);
    Ok(bytes)
}

pub fn usage_reservation_close_feature(value: Value) -> Result<Value, String> {
    let mut evidence = value.clone();
    let signature = evidence
        .as_object_mut()
        .ok_or("reservation close must be an object")?
        .remove("actor_sig")
        .ok_or("reservation close must be signed")?;
    let (operation, domain) = match evidence["op"].as_str() {
        Some("close_usage_reservation") => ("close", "mayhem-close-usage-reservation-feature-v1"),
        Some("expire_usage_reservation") => {
            ("expire", "mayhem-expire-usage-reservation-feature-v1")
        }
        _ => return Err("unsupported reservation close operation".into()),
    };
    let bytes =
        stable_json_bytes(&json!({"domain": domain, "evidence": evidence, "actor_sig": signature}))
            .map_err(|e| e.to_string())?;
    let key = format!(
        "receipt/{}/{}/{}/{}",
        operation,
        value["billing_epoch"]
            .as_u64()
            .ok_or("reservation close has no epoch")?,
        value["reservation_id"]
            .as_str()
            .ok_or("reservation close has no identity")?,
        blake3::hash(&bytes).to_hex()
    );
    Ok(json!({"feature": "mayhem", "key": key, "value": value}))
}

pub fn canonical_usage_receipt_hash(receipt: &Value) -> Result<String, String> {
    let bytes =
        stable_json_bytes(&json!({"domain": "mayhem-canonical-receipt-v1", "value": receipt}))
            .map_err(|e| e.to_string())?;
    Ok(blake3::hash(&bytes).to_hex().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reservation_close_matches_intercom_contract_vectors() {
        // Generated by the actual contract's closeUsageReservationFeatureKey,
        // including its stable JSON and actor-signature binding (contract 28).
        // The close evidence carries CONTRACT_VERSION, so these digests change
        // whenever the contract version changes; regenerate them from
        // intercom/contract/contract.js, never from this crate.
        let binding = json!({"billing_epoch":185,"reservation_id":"11".repeat(32),
            "reservation_expires_after_epoch":209,"reservation_receipt_grace_epochs":6,
            "billing_id":"22".repeat(32),"billing_attempt":0,"session_id":"33".repeat(32),
            "user":"44".repeat(32),"rail":"tnk","provider":"55".repeat(32),"payout_revision":"66".repeat(32)});
        for (expiry, digest) in [
            (
                false,
                "b2fde61528a908aa70660f7c0ecf07ee0fcefb9fefc50c8f0b1620cdb7163a2c",
            ),
            (
                true,
                "9dbb792758e31729ef4029d2d91454610683104547e117152ef111b729e61372",
            ),
        ] {
            let mut value = usage_reservation_close_value(
                &binding,
                None,
                expiry,
                1788796927,
                "provider_session_ended",
            )
            .unwrap();
            let unsigned_bytes = usage_reservation_close_signing_bytes(&value).unwrap();
            value["actor_sig"] = json!("aa".repeat(64));
            assert_eq!(
                usage_reservation_close_signing_bytes(&value).unwrap(),
                unsigned_bytes
            );
            let feature = usage_reservation_close_feature(value).unwrap();
            assert_eq!(
                feature["key"],
                format!(
                    "receipt/{}/185/{}/{}",
                    if expiry { "expire" } else { "close" },
                    "11".repeat(32),
                    digest
                )
            );
        }
    }
}
