// This runner is auto-generated by Brittle

import { default as test } from 'brittle';

async function runTests() {
    test.pause();
    await import('./index.test.js');
    await import('./config/configModule.test.js');
    await import('./cli/commandHandler.test.js');
    await import('./utils/utils.test.js');
    await import('./messages/messages.test.js');
    await import('./network/networkModule.test.js')
    await import('./state/stateModule.test.js');
    test.resume();
}

await runTests();
