// This runner is auto-generated by Brittle

import { default as test } from 'brittle';

async function runTests() {
	test.pause();
	await import('./network/networkModule.test.js')
	await import('./state/stateModule.test.js');
	await import('./utils/utils.test.js');
	await import('./messages/messages.test.js');
	test.resume();
}

await runTests();
