// This runner is auto-generated by Brittle

import { default as test } from 'brittle';

async function runTests() {
	test.pause();
	await import('./applyOperations.test.js');
	await import('./operationHelpers.test.js');
	test.resume();
}

await runTests();
