[package]
name = "mayhem-attestation-verifier"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "mayhem-attestation-verifier"
path = "src/main.rs"

[dependencies]
base64 = "0.22"
dcap-qvl = { version = "0.5.2", default-features = false, features = ["std", "rustcrypto", "default-x509"] }
hex = "0.4"
mayhem-attestation = { path = "../mayhem-attestation" }
mayhem-proto = { path = "../mayhem-proto" }
p256 = { version = "0.13", default-features = false, features = ["ecdsa", "std"] }
rsa = { version = "0.9", default-features = false, features = ["sha2", "std", "u64_digit"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sev = { version = "8.0.0", default-features = false, features = ["snp", "crypto_nossl"] }
sha2 = "0.10"
subtle = "2"
thiserror = "2"
url = "2"
x509-cert = "0.2"

[dev-dependencies]
rand_chacha = "0.3"
rand_core = "0.6"
