var b4a = require('b4a');
// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

exports.OperationType = {
  "UNKNOWN": 0,
  "ADD_ADMIN": 1,
  "DISABLE_INITIALIZATION": 2,
  "BALANCE_INITIALIZATION": 3,
  "APPEND_WHITELIST": 4,
  "ADD_WRITER": 5,
  "REMOVE_WRITER": 6,
  "ADMIN_RECOVERY": 7,
  "ADD_INDEXER": 8,
  "REMOVE_INDEXER": 9,
  "BAN_VALIDATOR": 10,
  "BOOTSTRAP_DEPLOYMENT": 11,
  "TX": 12,
  "TRANSFER": 13
}

var CoreAdminOperation = exports.CoreAdminOperation = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var AdminControlOperation = exports.AdminControlOperation = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var BalanceInitializationOperation = exports.BalanceInitializationOperation = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var TransferOperation = exports.TransferOperation = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var RoleAccessOperation = exports.RoleAccessOperation = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var TxOperation = exports.TxOperation = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var BootstrapDeploymentOperation = exports.BootstrapDeploymentOperation = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Operation = exports.Operation = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineCoreAdminOperation()
defineAdminControlOperation()
defineBalanceInitializationOperation()
defineTransferOperation()
defineRoleAccessOperation()
defineTxOperation()
defineBootstrapDeploymentOperation()
defineOperation()

function defineCoreAdminOperation () {
  CoreAdminOperation.encodingLength = encodingLength
  CoreAdminOperation.encode = encode
  CoreAdminOperation.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.tx)) {
      var len = encodings.bytes.encodingLength(obj.tx)
      length += 1 + len
    }
    if (defined(obj.txv)) {
      var len = encodings.bytes.encodingLength(obj.txv)
      length += 1 + len
    }
    if (defined(obj.iw)) {
      var len = encodings.bytes.encodingLength(obj.iw)
      length += 1 + len
    }
    if (defined(obj.in)) {
      var len = encodings.bytes.encodingLength(obj.in)
      length += 1 + len
    }
    if (defined(obj.is)) {
      var len = encodings.bytes.encodingLength(obj.is)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = b4a.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.tx)) {
      buf[offset++] = 10
      encodings.bytes.encode(obj.tx, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.txv)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.txv, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.iw)) {
      buf[offset++] = 26
      encodings.bytes.encode(obj.iw, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.in)) {
      buf[offset++] = 34
      encodings.bytes.encode(obj.in, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.is)) {
      buf[offset++] = 42
      encodings.bytes.encode(obj.is, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      tx: null,
      txv: null,
      iw: null,
      in: null,
      is: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.tx = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        obj.txv = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 3:
        obj.iw = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 4:
        obj.in = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 5:
        obj.is = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineAdminControlOperation () {
  AdminControlOperation.encodingLength = encodingLength
  AdminControlOperation.encode = encode
  AdminControlOperation.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.tx)) {
      var len = encodings.bytes.encodingLength(obj.tx)
      length += 1 + len
    }
    if (defined(obj.txv)) {
      var len = encodings.bytes.encodingLength(obj.txv)
      length += 1 + len
    }
    if (defined(obj.ia)) {
      var len = encodings.bytes.encodingLength(obj.ia)
      length += 1 + len
    }
    if (defined(obj.in)) {
      var len = encodings.bytes.encodingLength(obj.in)
      length += 1 + len
    }
    if (defined(obj.is)) {
      var len = encodings.bytes.encodingLength(obj.is)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = b4a.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.tx)) {
      buf[offset++] = 10
      encodings.bytes.encode(obj.tx, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.txv)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.txv, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.ia)) {
      buf[offset++] = 26
      encodings.bytes.encode(obj.ia, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.in)) {
      buf[offset++] = 34
      encodings.bytes.encode(obj.in, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.is)) {
      buf[offset++] = 42
      encodings.bytes.encode(obj.is, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      tx: null,
      txv: null,
      ia: null,
      in: null,
      is: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.tx = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        obj.txv = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 3:
        obj.ia = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 4:
        obj.in = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 5:
        obj.is = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineBalanceInitializationOperation () {
  BalanceInitializationOperation.encodingLength = encodingLength
  BalanceInitializationOperation.encode = encode
  BalanceInitializationOperation.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.tx)) {
      var len = encodings.bytes.encodingLength(obj.tx)
      length += 1 + len
    }
    if (defined(obj.txv)) {
      var len = encodings.bytes.encodingLength(obj.txv)
      length += 1 + len
    }
    if (defined(obj.ia)) {
      var len = encodings.bytes.encodingLength(obj.ia)
      length += 1 + len
    }
    if (defined(obj.am)) {
      var len = encodings.bytes.encodingLength(obj.am)
      length += 1 + len
    }
    if (defined(obj.in)) {
      var len = encodings.bytes.encodingLength(obj.in)
      length += 1 + len
    }
    if (defined(obj.is)) {
      var len = encodings.bytes.encodingLength(obj.is)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = b4a.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.tx)) {
      buf[offset++] = 10
      encodings.bytes.encode(obj.tx, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.txv)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.txv, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.ia)) {
      buf[offset++] = 26
      encodings.bytes.encode(obj.ia, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.am)) {
      buf[offset++] = 34
      encodings.bytes.encode(obj.am, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.in)) {
      buf[offset++] = 42
      encodings.bytes.encode(obj.in, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.is)) {
      buf[offset++] = 50
      encodings.bytes.encode(obj.is, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      tx: null,
      txv: null,
      ia: null,
      am: null,
      in: null,
      is: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.tx = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        obj.txv = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 3:
        obj.ia = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 4:
        obj.am = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 5:
        obj.in = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 6:
        obj.is = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineTransferOperation () {
  TransferOperation.encodingLength = encodingLength
  TransferOperation.encode = encode
  TransferOperation.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.tx)) {
      var len = encodings.bytes.encodingLength(obj.tx)
      length += 1 + len
    }
    if (defined(obj.txv)) {
      var len = encodings.bytes.encodingLength(obj.txv)
      length += 1 + len
    }
    if (defined(obj.to)) {
      var len = encodings.bytes.encodingLength(obj.to)
      length += 1 + len
    }
    if (defined(obj.am)) {
      var len = encodings.bytes.encodingLength(obj.am)
      length += 1 + len
    }
    if (defined(obj.in)) {
      var len = encodings.bytes.encodingLength(obj.in)
      length += 1 + len
    }
    if (defined(obj.is)) {
      var len = encodings.bytes.encodingLength(obj.is)
      length += 1 + len
    }
    if (defined(obj.va)) {
      var len = encodings.bytes.encodingLength(obj.va)
      length += 1 + len
    }
    if (defined(obj.vn)) {
      var len = encodings.bytes.encodingLength(obj.vn)
      length += 1 + len
    }
    if (defined(obj.vs)) {
      var len = encodings.bytes.encodingLength(obj.vs)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = b4a.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.tx)) {
      buf[offset++] = 10
      encodings.bytes.encode(obj.tx, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.txv)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.txv, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.to)) {
      buf[offset++] = 26
      encodings.bytes.encode(obj.to, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.am)) {
      buf[offset++] = 34
      encodings.bytes.encode(obj.am, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.in)) {
      buf[offset++] = 42
      encodings.bytes.encode(obj.in, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.is)) {
      buf[offset++] = 50
      encodings.bytes.encode(obj.is, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.va)) {
      buf[offset++] = 58
      encodings.bytes.encode(obj.va, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.vn)) {
      buf[offset++] = 66
      encodings.bytes.encode(obj.vn, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.vs)) {
      buf[offset++] = 74
      encodings.bytes.encode(obj.vs, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      tx: null,
      txv: null,
      to: null,
      am: null,
      in: null,
      is: null,
      va: null,
      vn: null,
      vs: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.tx = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        obj.txv = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 3:
        obj.to = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 4:
        obj.am = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 5:
        obj.in = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 6:
        obj.is = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 7:
        obj.va = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 8:
        obj.vn = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 9:
        obj.vs = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineRoleAccessOperation () {
  RoleAccessOperation.encodingLength = encodingLength
  RoleAccessOperation.encode = encode
  RoleAccessOperation.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.tx)) {
      var len = encodings.bytes.encodingLength(obj.tx)
      length += 1 + len
    }
    if (defined(obj.txv)) {
      var len = encodings.bytes.encodingLength(obj.txv)
      length += 1 + len
    }
    if (defined(obj.iw)) {
      var len = encodings.bytes.encodingLength(obj.iw)
      length += 1 + len
    }
    if (defined(obj.in)) {
      var len = encodings.bytes.encodingLength(obj.in)
      length += 1 + len
    }
    if (defined(obj.is)) {
      var len = encodings.bytes.encodingLength(obj.is)
      length += 1 + len
    }
    if (defined(obj.va)) {
      var len = encodings.bytes.encodingLength(obj.va)
      length += 1 + len
    }
    if (defined(obj.vn)) {
      var len = encodings.bytes.encodingLength(obj.vn)
      length += 1 + len
    }
    if (defined(obj.vs)) {
      var len = encodings.bytes.encodingLength(obj.vs)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = b4a.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.tx)) {
      buf[offset++] = 10
      encodings.bytes.encode(obj.tx, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.txv)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.txv, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.iw)) {
      buf[offset++] = 26
      encodings.bytes.encode(obj.iw, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.in)) {
      buf[offset++] = 34
      encodings.bytes.encode(obj.in, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.is)) {
      buf[offset++] = 42
      encodings.bytes.encode(obj.is, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.va)) {
      buf[offset++] = 50
      encodings.bytes.encode(obj.va, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.vn)) {
      buf[offset++] = 58
      encodings.bytes.encode(obj.vn, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.vs)) {
      buf[offset++] = 66
      encodings.bytes.encode(obj.vs, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      tx: null,
      txv: null,
      iw: null,
      in: null,
      is: null,
      va: null,
      vn: null,
      vs: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.tx = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        obj.txv = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 3:
        obj.iw = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 4:
        obj.in = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 5:
        obj.is = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 6:
        obj.va = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 7:
        obj.vn = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 8:
        obj.vs = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineTxOperation () {
  TxOperation.encodingLength = encodingLength
  TxOperation.encode = encode
  TxOperation.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.tx)) {
      var len = encodings.bytes.encodingLength(obj.tx)
      length += 1 + len
    }
    if (defined(obj.txv)) {
      var len = encodings.bytes.encodingLength(obj.txv)
      length += 1 + len
    }
    if (defined(obj.iw)) {
      var len = encodings.bytes.encodingLength(obj.iw)
      length += 1 + len
    }
    if (defined(obj.ch)) {
      var len = encodings.bytes.encodingLength(obj.ch)
      length += 1 + len
    }
    if (defined(obj.bs)) {
      var len = encodings.bytes.encodingLength(obj.bs)
      length += 1 + len
    }
    if (defined(obj.mbs)) {
      var len = encodings.bytes.encodingLength(obj.mbs)
      length += 1 + len
    }
    if (defined(obj.in)) {
      var len = encodings.bytes.encodingLength(obj.in)
      length += 1 + len
    }
    if (defined(obj.is)) {
      var len = encodings.bytes.encodingLength(obj.is)
      length += 1 + len
    }
    if (defined(obj.va)) {
      var len = encodings.bytes.encodingLength(obj.va)
      length += 1 + len
    }
    if (defined(obj.vn)) {
      var len = encodings.bytes.encodingLength(obj.vn)
      length += 1 + len
    }
    if (defined(obj.vs)) {
      var len = encodings.bytes.encodingLength(obj.vs)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = b4a.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.tx)) {
      buf[offset++] = 10
      encodings.bytes.encode(obj.tx, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.txv)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.txv, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.iw)) {
      buf[offset++] = 26
      encodings.bytes.encode(obj.iw, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.ch)) {
      buf[offset++] = 34
      encodings.bytes.encode(obj.ch, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.bs)) {
      buf[offset++] = 42
      encodings.bytes.encode(obj.bs, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.mbs)) {
      buf[offset++] = 50
      encodings.bytes.encode(obj.mbs, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.in)) {
      buf[offset++] = 58
      encodings.bytes.encode(obj.in, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.is)) {
      buf[offset++] = 66
      encodings.bytes.encode(obj.is, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.va)) {
      buf[offset++] = 74
      encodings.bytes.encode(obj.va, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.vn)) {
      buf[offset++] = 82
      encodings.bytes.encode(obj.vn, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.vs)) {
      buf[offset++] = 90
      encodings.bytes.encode(obj.vs, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      tx: null,
      txv: null,
      iw: null,
      ch: null,
      bs: null,
      mbs: null,
      in: null,
      is: null,
      va: null,
      vn: null,
      vs: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.tx = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        obj.txv = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 3:
        obj.iw = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 4:
        obj.ch = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 5:
        obj.bs = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 6:
        obj.mbs = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 7:
        obj.in = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 8:
        obj.is = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 9:
        obj.va = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 10:
        obj.vn = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 11:
        obj.vs = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineBootstrapDeploymentOperation () {
  BootstrapDeploymentOperation.encodingLength = encodingLength
  BootstrapDeploymentOperation.encode = encode
  BootstrapDeploymentOperation.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.tx)) {
      var len = encodings.bytes.encodingLength(obj.tx)
      length += 1 + len
    }
    if (defined(obj.txv)) {
      var len = encodings.bytes.encodingLength(obj.txv)
      length += 1 + len
    }
    if (defined(obj.bs)) {
      var len = encodings.bytes.encodingLength(obj.bs)
      length += 1 + len
    }
    if (defined(obj.ic)) {
      var len = encodings.bytes.encodingLength(obj.ic)
      length += 1 + len
    }
    if (defined(obj.in)) {
      var len = encodings.bytes.encodingLength(obj.in)
      length += 1 + len
    }
    if (defined(obj.is)) {
      var len = encodings.bytes.encodingLength(obj.is)
      length += 1 + len
    }
    if (defined(obj.va)) {
      var len = encodings.bytes.encodingLength(obj.va)
      length += 1 + len
    }
    if (defined(obj.vn)) {
      var len = encodings.bytes.encodingLength(obj.vn)
      length += 1 + len
    }
    if (defined(obj.vs)) {
      var len = encodings.bytes.encodingLength(obj.vs)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = b4a.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.tx)) {
      buf[offset++] = 10
      encodings.bytes.encode(obj.tx, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.txv)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.txv, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.bs)) {
      buf[offset++] = 26
      encodings.bytes.encode(obj.bs, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.ic)) {
      buf[offset++] = 34
      encodings.bytes.encode(obj.ic, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.in)) {
      buf[offset++] = 42
      encodings.bytes.encode(obj.in, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.is)) {
      buf[offset++] = 50
      encodings.bytes.encode(obj.is, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.va)) {
      buf[offset++] = 58
      encodings.bytes.encode(obj.va, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.vn)) {
      buf[offset++] = 66
      encodings.bytes.encode(obj.vn, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.vs)) {
      buf[offset++] = 74
      encodings.bytes.encode(obj.vs, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      tx: null,
      txv: null,
      bs: null,
      ic: null,
      in: null,
      is: null,
      va: null,
      vn: null,
      vs: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.tx = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        obj.txv = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 3:
        obj.bs = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 4:
        obj.ic = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 5:
        obj.in = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 6:
        obj.is = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 7:
        obj.va = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 8:
        obj.vn = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 9:
        obj.vs = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineOperation () {
  Operation.encodingLength = encodingLength
  Operation.encode = encode
  Operation.decode = decode

  function encodingLength (obj) {
    var length = 0
    if ((+defined(obj.cao) + +defined(obj.aco) + +defined(obj.bio) + +defined(obj.tro) + +defined(obj.rao) + +defined(obj.bdo) + +defined(obj.txo)) > 1) throw new Error("only one of the properties defined in oneof value can be set")
    if (defined(obj.type)) {
      var len = encodings.enum.encodingLength(obj.type)
      length += 1 + len
    }
    if (defined(obj.address)) {
      var len = encodings.bytes.encodingLength(obj.address)
      length += 1 + len
    }
    if (defined(obj.cao)) {
      var len = CoreAdminOperation.encodingLength(obj.cao)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.aco)) {
      var len = AdminControlOperation.encodingLength(obj.aco)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.bio)) {
      var len = BalanceInitializationOperation.encodingLength(obj.bio)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.tro)) {
      var len = TransferOperation.encodingLength(obj.tro)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.rao)) {
      var len = RoleAccessOperation.encodingLength(obj.rao)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.bdo)) {
      var len = BootstrapDeploymentOperation.encodingLength(obj.bdo)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.txo)) {
      var len = TxOperation.encodingLength(obj.txo)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = b4a.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if ((+defined(obj.cao) + +defined(obj.aco) + +defined(obj.bio) + +defined(obj.tro) + +defined(obj.rao) + +defined(obj.bdo) + +defined(obj.txo)) > 1) throw new Error("only one of the properties defined in oneof value can be set")
    if (defined(obj.type)) {
      buf[offset++] = 8
      encodings.enum.encode(obj.type, buf, offset)
      offset += encodings.enum.encode.bytes
    }
    if (defined(obj.address)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.address, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.cao)) {
      buf[offset++] = 26
      varint.encode(CoreAdminOperation.encodingLength(obj.cao), buf, offset)
      offset += varint.encode.bytes
      CoreAdminOperation.encode(obj.cao, buf, offset)
      offset += CoreAdminOperation.encode.bytes
    }
    if (defined(obj.aco)) {
      buf[offset++] = 34
      varint.encode(AdminControlOperation.encodingLength(obj.aco), buf, offset)
      offset += varint.encode.bytes
      AdminControlOperation.encode(obj.aco, buf, offset)
      offset += AdminControlOperation.encode.bytes
    }
    if (defined(obj.bio)) {
      buf[offset++] = 42
      varint.encode(BalanceInitializationOperation.encodingLength(obj.bio), buf, offset)
      offset += varint.encode.bytes
      BalanceInitializationOperation.encode(obj.bio, buf, offset)
      offset += BalanceInitializationOperation.encode.bytes
    }
    if (defined(obj.tro)) {
      buf[offset++] = 50
      varint.encode(TransferOperation.encodingLength(obj.tro), buf, offset)
      offset += varint.encode.bytes
      TransferOperation.encode(obj.tro, buf, offset)
      offset += TransferOperation.encode.bytes
    }
    if (defined(obj.rao)) {
      buf[offset++] = 58
      varint.encode(RoleAccessOperation.encodingLength(obj.rao), buf, offset)
      offset += varint.encode.bytes
      RoleAccessOperation.encode(obj.rao, buf, offset)
      offset += RoleAccessOperation.encode.bytes
    }
    if (defined(obj.bdo)) {
      buf[offset++] = 66
      varint.encode(BootstrapDeploymentOperation.encodingLength(obj.bdo), buf, offset)
      offset += varint.encode.bytes
      BootstrapDeploymentOperation.encode(obj.bdo, buf, offset)
      offset += BootstrapDeploymentOperation.encode.bytes
    }
    if (defined(obj.txo)) {
      buf[offset++] = 74
      varint.encode(TxOperation.encodingLength(obj.txo), buf, offset)
      offset += varint.encode.bytes
      TxOperation.encode(obj.txo, buf, offset)
      offset += TxOperation.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      type: 0,
      address: null,
      cao: null,
      aco: null,
      bio: null,
      tro: null,
      rao: null,
      bdo: null,
      txo: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.type = encodings.enum.decode(buf, offset)
        offset += encodings.enum.decode.bytes
        break
        case 2:
        obj.address = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 3:
        delete obj.aco
        delete obj.bio
        delete obj.tro
        delete obj.rao
        delete obj.bdo
        delete obj.txo
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.cao = CoreAdminOperation.decode(buf, offset, offset + len)
        offset += CoreAdminOperation.decode.bytes
        break
        case 4:
        delete obj.cao
        delete obj.bio
        delete obj.tro
        delete obj.rao
        delete obj.bdo
        delete obj.txo
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.aco = AdminControlOperation.decode(buf, offset, offset + len)
        offset += AdminControlOperation.decode.bytes
        break
        case 5:
        delete obj.cao
        delete obj.aco
        delete obj.tro
        delete obj.rao
        delete obj.bdo
        delete obj.txo
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.bio = BalanceInitializationOperation.decode(buf, offset, offset + len)
        offset += BalanceInitializationOperation.decode.bytes
        break
        case 6:
        delete obj.cao
        delete obj.aco
        delete obj.bio
        delete obj.rao
        delete obj.bdo
        delete obj.txo
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.tro = TransferOperation.decode(buf, offset, offset + len)
        offset += TransferOperation.decode.bytes
        break
        case 7:
        delete obj.cao
        delete obj.aco
        delete obj.bio
        delete obj.tro
        delete obj.bdo
        delete obj.txo
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.rao = RoleAccessOperation.decode(buf, offset, offset + len)
        offset += RoleAccessOperation.decode.bytes
        break
        case 8:
        delete obj.cao
        delete obj.aco
        delete obj.bio
        delete obj.tro
        delete obj.rao
        delete obj.txo
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.bdo = BootstrapDeploymentOperation.decode(buf, offset, offset + len)
        offset += BootstrapDeploymentOperation.decode.bytes
        break
        case 9:
        delete obj.cao
        delete obj.aco
        delete obj.bio
        delete obj.tro
        delete obj.rao
        delete obj.bdo
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.txo = TxOperation.decode(buf, offset, offset + len)
        offset += TxOperation.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
